### ISSUE TITLE
Porter unable to install bundle and giving rpc errors

### ISSUE THREAD

**Issue by nitishdsharma** [getporter/porter#2473] opened 2022-11-29 07:48 UTC
Creating a new porter bundle and trying to install it locally but its rendering rpc errors on porter install command.

**Error messages**

`rpc error: code = DeadlineExceeded desc = server selection error: context deadline exceeded, current topology: { Type: Single, Servers: [{ Addr: localhost:27018, Type: Unknown }, ] }
could not retrieve the installation record: could not read storage schema document: rpc error: code = DeadlineExceeded desc = server selection error: context deadline exceeded, current topology: { Type: Single, Servers: [{ Addr: localhost:27018, Type: Unknown }, ] }
could not retrieve the installation record: could not read storage schema document: rpc error: code = DeadlineExceeded desc = server selection error: context deadline exceeded, current topology: { Type: Single, Servers: [{ Addr: localhost:27018, Type: Unknown }, ] }
`

**Comment by VinozzZ** [comment] 2022-11-29 15:02
Hi there, thanks for reporting your issue. Do you mind to share which version of porter you are using and the porter command you ran that produced this error?

**Comment by carolynvs** [comment] 2022-11-29 15:32
By default, if you do not configure differently in ~/.porter/config.yaml, Porter will use the [mongodb-docker storage plugin](https://getporter.org/plugins/mongodb-docker/), which runs a mongo container on porter 27018 named `porter-mongodb-docker-plugin`.

```
$ docker ps
...
b56beddb3f0e   95a66c5d5e6c   "docker-entrypoint.s…"   6 weeks ago   Up 6 weeks   0.0.0.0:27018->27017/tcp  porter-mongodb-docker-plugin
```

Can you check your [porter configuration file](https://getporter.org/configuration/#config-file) (located in ~/.porter, named config.toml or config.yaml or config.json) and verify that you do not have a storage plugin set? Then run `docker ps` to see if docker is running, and if you have that container started?

One cause of that error is that porter was unable to start the mongo container and then it fails to connect.

**Comment by nitishdsharma** [comment] 2022-12-15 14:50
@VinozzZ The porter version is **porter v1.0.1 (91676a6c)**
Command which triggered this issue: porter install cloudcasa --param cluster_id=<clusterid>

**Comment by kichristensen** [comment] 2024-05-24 20:58
@nitishdsharma Sorry for lack for reply, because the issue is so old and the version of Porter is old, I will close it. If you are still having problems please create a new issue.

**Closed by kichristensen** 2024-05-24 20:58 UTC
