### ISSUE TITLE
Add the all-contributors integration

### ISSUE THREAD

**Issue by nhcarrigan** [getporter/porter#1336] opened 2020-10-22 20:46 UTC
**Is your feature request related to a problem? Please describe.**

Currently, new contributors submit a PR to add their name to the recognition file.

**Describe the solution you'd like**

Rather than a manual workflow, the [all contributors](https://allcontributors.org/) integration could be enabled to allow a more automated process:

A maintainer can comment on a PR to add a contributor, and the integration will open a new PR to add the contributor to the table.

**Describe alternatives you've considered**

**Additional context**

Example of the table generated:
![image](https://user-images.githubusercontent.com/63889819/96928044-da836600-146c-11eb-9280-5858a0b17879.png)

Issue opened at @iennae's request. 🙂

**Comment by carolynvs** [comment] 2020-10-23 18:06
Yes! I would totally love to move to this. I was musing over it in #1167 and it sounds like people would like that.

**Comment by carolynvs** [comment] 2022-03-11 22:03
Duplicate of #1167

**Closed by carolynvs** 2022-03-11 22:03 UTC
Labels: meta, 2 - 🍕, suggestion
