### ISSUE TITLE
Can no longer provide kubeconfig as credential to a bundle on installation

### ISSUE THREAD

**Issue by andreas-baus** [getporter/porter#1809] opened 2021-10-26 12:39 UTC
## Describe the bug
Since Porter v1.0.0-alpha.4, I am no longer able to provide a kubeconfig file as a credential to a bundle during installation.

## To Reproduce
1. Create a file `kubeconfig.json` with the following content (substituting the path to a valid kubeconfig file for a suitable test environment)
```json
{
  "credentials": [
    {
      "name": "kubeconfig",
      "source": {
        "path": "/tmp/test/kubeconfig.yml"
      }
    }
  ]
}
```
2. Create a file `parameters.json` with the following content:
```json
{
  "parameters": [
    {
      "name": "registry",
      "source": {
        "value": "test-registry"
      }
    },
    {
      "name": "username",
      "source": {
        "value": "test-user"
      }
    },
    {
      "name": "password",
      "source": {
        "value": "test-pass"
      }
    },
    {
      "name": "namespace",
      "source": {
        "value": "default"
      }
    }
  ]
}
```
3. Run this porter command: `porter install ips --reference registry.centros.cloud/library/image-pull-secret:v1.0.1 -c ./kubeconfig.json -p ./params.json`

4. With Porter v1.0.0.alpha3, this command completes successfully:
```
vmuser@sandbox:~/test/porter$ porter --version
porter v1.0.0-alpha.3 (09840b4c)

vmuser@sandbox:~/test/porter$ porter install ips --reference registry.centros.cloud/library/image-pull-secret:v1.0.1 -c ./kubeconfig.json -p ./params.json
installing ips...
executing install action from image-pull-secret (installation: ips)
Prepare manifest

apiVersion: v1
kind: Secret
metadata:
  name: ips
  labels:
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0ZXN0LXJlZ2lzdHJ5Ijp7InVzZXJuYW1lIjoidGVzdC11c2VyIiwicGFzc3dvcmQiOiJ0ZXN0LXBhc3MiLCJlbWFpbCI6IiIsImF1dGgiOiJkR1Z6ZEMxMWMyVnlPblJsYzNRdGNHRnpjdz09In19fQ==
Create image pull secret
secret/ips configured
execution completed successfully!

vmuser@sandbox:~/test/porter$ kubectl get secret/ips
NAME   TYPE                             DATA   AGE
ips    kubernetes.io/dockerconfigjson   1      3s
```

5. With v1.0.0.alpha.4, in an otherwise completely identical environment, an error occurs (also tested with alpha.5; behaviour still persists):
```
vmuser@sandbox:~/test/porter$ porter --version
porter v1.0.0-alpha.4 (4b2126c0)

vmuser@sandbox:~/test/porter$ porter install ips --reference registry.centros.cloud/library/image-pull-secret:v1.0.1 -c ./kubeconfig.json -p ./params.json
installing ips...
Error: could not load credentials: bundle requires credential for kubeconfig

```

## Expected behavior
Porter should still succeed at installing the bundle

## Porter Command and Output
See above; additionally, this is the output of the command above when adding the `--debug` parameter, in case that helps identify the issue:
```
detecting Porter config in /home/vmuser/.porter
loaded Porter config from 
Using '' namespace from configuration
Pulling bundle registry.centros.cloud/library/image-pull-secret:v1.0.1
waiting for the mongo service to be ready
Connecting to mongo database porter at [localhost:27018]
resolving parameters for installation /ips
No parameter sources defined, skipping
Pulling bundle registry.centros.cloud/library/image-pull-secret:v1.0.1
resolving parameters for installation /ips
No parameter sources defined, skipping
installing ips...
{"credentials":{"kubeconfig":{"path":"/root/.kube/config","required":true}},"custom":{"sh.porter":{"commit":"3018b91c","manifest":"LS0tCm5hbWU6IGltYWdlLXB1bGwtc2VjcmV0CnZlcnNpb246IDEuMC4xCmRlc2NyaXB0aW9uOiBBIHBvcnRlciBidW5kbGUgZm9yIGNyZWF0aW5nIGs4cyBpbWFnZSBwdWxsIHNlY3JldHMKcmVnaXN0cnk6IHJlZ2lzdHJ5LmNlbnRyb3MuY2xvdWQvbGlicmFyeQpkb2NrZXJmaWxlOiBEb2NrZXJmaWxlLnRtcGwKbWl4aW5zOgogIC0gZXhlYwogIC0ga3ViZXJuZXRlcwpwYXJhbWV0ZXJzOgogIC0gbmFtZTogdXNlcm5hbWUKICAgIHR5cGU6IHN0cmluZwogIC0gbmFtZTogcGFzc3dvcmQKICAgIHR5cGU6IHN0cmluZwogIC0gbmFtZTogcmVnaXN0cnkKICAgIHR5cGU6IHN0cmluZwogIC0gbmFtZTogZW1haWwKICAgIHR5cGU6IHN0cmluZwogICAgZGVmYXVsdDogIiIKICAtIG5hbWU6IG5hbWVzcGFjZQogICAgdHlwZTogc3RyaW5nCiAgICBkZWZhdWx0OiBkZWZhdWx0CmNyZWRlbnRpYWxzOgogIC0gbmFtZToga3ViZWNvbmZpZwogICAgcGF0aDogL3Jvb3QvLmt1YmUvY29uZmlnCmluc3RhbGw6CiAgLSBleGVjOgogICAgICBkZXNjcmlwdGlvbjogUHJlcGFyZSBtYW5pZmVzdAogICAgICBjb21tYW5kOiAiLi9oZWxwZXJzLnNoIgogICAgICBhcmd1bWVudHM6CiAgICAgICAgLSBwcmVwYXJlLW1hbmlmZXN0CiAgICAgICAgLSAiXCJ7eyBpbnN0YWxsYXRpb24ubmFtZSB9fVwiIgogIC0ga3ViZXJuZXRlczoKICAgICAgZGVzY3JpcHRpb246IENyZWF0ZSBpbWFnZSBwdWxsIHNlY3JldAogICAgICBtYW5pZmVzdHM6CiAgICAgICAgLSBrOHMvaXBzLnlhbWwKICAgICAgd2FpdDogdHJ1ZQp1cGdyYWRlOgogIC0gZXhlYzoKICAgICAgZGVzY3JpcHRpb246IFByZXBhcmUgbWFuaWZlc3QKICAgICAgY29tbWFuZDogIi4vaGVscGVycy5zaCIKICAgICAgYXJndW1lbnRzOgogICAgICAgIC0gcHJlcGFyZS1tYW5pZmVzdAogICAgICAgIC0gIlwie3sgaW5zdGFsbGF0aW9uLm5hbWUgfX1cIiIKICAtIGt1YmVybmV0ZXM6CiAgICAgIGRlc2NyaXB0aW9uOiBVcGRhdGUgaW1hZ2UgcHVsbCBzZWNyZXQKICAgICAgbWFuaWZlc3RzOgogICAgICAgIC0gazhzL2lwcy55YW1sCiAgICAgIHdhaXQ6IHRydWUKdW5pbnN0YWxsOgogIC0gZXhlYzoKICAgICAgZGVzY3JpcHRpb246IERlbGV0ZSBpbWFnZSBwdWxsIHNlY3JldAogICAgICBjb21tYW5kOiAiLi9oZWxwZXJzLnNoIgogICAgICBhcmd1bWVudHM6CiAgICAgICAgLSBkZWxldGUtc2VjcmV0Cg==","manifestDigest":"e59e92fbd95df45c70cdded6617a33aa95789266e2d442e9c8f82d7b6f055e0f","mixins":{"exec":{},"kubernetes":{}},"version":"v0.38.1"},"sh.porter.file-parameters":{}},"definitions":{"email-parameter":{"default":"","type":"string"},"namespace-parameter":{"default":"default","type":"string"},"password-parameter":{"type":"string"},"porter-debug-parameter":{"$comment":"porter-internal","$id":"https://porter.sh/generated-bundle/#porter-debug","default":false,"description":"Print debug information from Porter when executing the bundle","type":"boolean"},"registry-parameter":{"type":"string"},"username-parameter":{"type":"string"}},"description":"A porter bundle for creating k8s image pull secrets","invocationImages":[{"contentDigest":"sha256:d2c42cc57e1c2b28dfdb1c084b2bb6dfb5a5bd573c00666f7bffd4f92e1e1a08","image":"registry.centros.cloud/library/image-pull-secret-installer:v1.0.1","imageType":"docker","mediaType":"application/vnd.docker.distribution.manifest.v2+json","size":2003}],"name":"image-pull-secret","parameters":{"email":{"definition":"email-parameter","destination":{"env":"EMAIL"}},"namespace":{"definition":"namespace-parameter","destination":{"env":"NAMESPACE"}},"password":{"definition":"password-parameter","destination":{"env":"PASSWORD"},"required":true},"porter-debug":{"definition":"porter-debug-parameter","description":"Print debug information from Porter when executing the bundle","destination":{"env":"PORTER_DEBUG"}},"registry":{"definition":"registry-parameter","destination":{"env":"REGISTRY"},"required":true},"username":{"definition":"username-parameter","destination":{"env":"USERNAME"},"required":true}},"requiredExtensions":["sh.porter.file-parameters"],"schemaVersion":"v1.0.0","version":"1.0.1"}
Error: could not load credentials: bundle requires credential for kubeconfig
``` 

## Version
See above.

**Comment by carolynvs** [comment] 2021-11-02 18:20
Thanks for the bug report! I located the regression and will work on getting a fix out. In the meantime, a workaround would be to 

1. Set the name in the credential set file, e.g. mycreds.
2. Import the credential set with `porter credentials apply ./creds.json`
3. Reference the name of the credential set when installing `porter install -c mycreds`.

**Comment by VinozzZ** [comment] 2022-01-24 21:34
Hi there, thanks again for reporting the issue. After some investigation, we found that the direct cause is the credential file path not being passed to the action execution code. However, the fix for this issue requires us to answer a bigger question, which is `if someone calls porter install -c somecreds.json” should be remember what was in that file so they can reuse it?`.
The initial intention of the `-c` flag is to give users the ability to do scripting with porter, which at the time there's isn't an non-interactive command to do that. Now porter has a new command `porter credentials apply`. It solves the original issue that `-c` was added for. 
I want to propose that we should remove the `-c` flag and have users who want to use a credential file to use the new `apply` command. This will not only reduce the code complexity of porter, but also provide a clear workflow. 
Do you have a use case that prevents you from using the `apply` command? I would love to hear your feedback on my proposal.
Thanks!

**Comment by carolynvs** [comment] 2022-01-25 16:06
Hey @vdice, since this would be a breaking change can you take a look at Yingrong's proposal above and weigh in?

Removing the ability to pass files to --param or --cred for install/upgrade/uninstall/invoke would simplify Porter's logic a bit now that we have the apply commands. What do you think?

**Comment by vdice** [comment] 2022-01-25 17:37
I don't have a strong opinion here.  Admittedly, old habits die hard and I do fairly often find myself supplying filepaths for `-p`/`-c`.  I suppose my only user argument to keep the functionality would be the simplicity of the one command (e.g. `porter install -p ./myparamset.json`) vs multiple, at least anytime the value set needs to be added/updated (e.g. `porter apply ./myparamset.json && porter install -p myparamset`).

However, it is a small inconvenience and I would defer to code simplification (especially if it proves tricky to juggle tracking values between those stored in porter and those provided via a filepath at action time).  As it sounds like the active maintainers (i.e. most familiar with the code and complexity) favor this simplification, I'd say the breaking change is warranted.

**Comment by carolynvs** [comment] 2022-01-25 18:06
The complexity comes up because of Porter's new ability to remember the values you passed previously so you don't have to specify them again.

```
$ porter install myblog -r getporter/wordpress:v1.0.0 --param name=carolyn -c myazurecreds
# installs porter

$ porter upgrade myblog --version 2.0.0
# reuses the parameters and credential sets specified during install, so they don't have to set them every time
# They can still override them with flags
```

If they specify a file, what should porter remember? 

1. Don't let them specify a file, so that we only have to remember the names of a parameter/credential set.
2. Let them specify a file, but don't remember anything and they need to specify it again later. This is inconsistent behavior that I think will be confusing.
3. When they specify a file, save it as a parameter/cred set and then remember its name. Then the question is... what do we name it and should the user see it when they run `porter credentials list`?

We were originally leaning towards the first solution because it seemed the most simple both in code and porter's expected behavior. But number 3 could be doable if we knew what we wanted to happen.

**Comment by Jemgoss** [comment] 2022-01-25 18:09
Just to be clear, the proposal is not to remove the -c and -p flags altogether, but to remove their interpretation as filenames instead of parameter-set and credential-set names? If that's the case then I'm all for it - not a fan of the dual meanings for those args anyway.

**Comment by Tatsinnit** [comment] 2022-01-26 01:00
☕ 💡 🐱  I will add 2 cent worth purely from my goto use I do with Porter, and then probably get everyone's thought and guidance that if there is no `-c` flag then what would it replace it with:

**Use case:**

Once I have my `porter bundle` publish I create the `creds` using the `porter credential generate kubecred --reference getporter/porter-installation-stuff:v0.1.0` and then I use this `porter credentials list` to manage multiple creds for various bundles and work.

Then when I need to invoke the `porter install` I do something like this: `porter install -c kubecred --reference   getporter/porter-installation-stuff:v0.1.0` https://porter.sh/quickstart/credentials/#specify-a-credential-with-a-credential-set 

So incase if we are removing the `-c` what it will be replaced with?

**Or Are we making it atomic**

By which I mean once the `credentials is created` since we used `--reference` field to use it we will not `-c` anymore and `porter can handle that mapping between the `credential generate reference` and `porter install --referenct` 

Thanks heaps in advance ❤️🙏☕️

**Comment by VinozzZ** [comment] 2022-01-26 15:07
> coffee bulb cat I will add 2 cent worth purely from my goto use I do with Porter, and then probably get everyone's thought and guidance that if there is no `-c` flag then what would it replace it with:
> 
> **Use case:**
> 
> Once I have my `porter bundle` publish I create the `creds` using the `porter credential generate kubecred --reference getporter/porter-installation-stuff:v0.1.0` and then I use this `porter credentials list` to manage multiple creds for various bundles and work.
> 
> Then when I need to invoke the `porter install` I do something like this: `porter install -c kubecred --reference getporter/porter-installation-stuff:v0.1.0` https://porter.sh/quickstart/credentials/#specify-a-credential-with-a-credential-set
> 
> So incase if we are removing the `-c` what it will be replaced with?
> 
> **Or Are we making it atomic**
> 
> By which I mean once the `credentials is created` since we used `--reference` field to use it we will not `-c` anymore and `porter` can handle that mapping between the `credential generate --reference xyz:1.0` and `porter install --reference xyz:1.0`
> 
> Thanks heaps in advance heartpraycoffee

Hi there, thank you for sharing your use case. Sorry that my original comment created the confusion. I'm only proposing to remove the capability to pass a file path to the `-c` and `-p` flags. From what I can see in your comment, you are passing in a credential set name. It should not be affected with my proposal. Hope this helps to make things more clear

**Comment by carolynvs** [comment] 2022-02-07 21:14
Let's give this until 2/10 and if we don't hear anything else, move forward with the proposal.

**Closed** 2022-02-25 22:01 UTC
Labels: bug, 1 - 🍫
