### ISSUE TITLE
Allow uninstall to proceed even if a mixin fails - possibly using a --doNotFailOnError flag

### ISSUE THREAD

**Issue by jasmdk** [getporter/porter#1377] opened 2020-11-25 12:40 UTC
In some cases, our bundles tend to get quite large, having a mix of various mixins and occasionally installation fails due to unforseen interruptions or circumstances. This can result in a bundle failing during install, but installing at again may also fail - we are using a helm3 mixin which will try to install the same release with the same name and complain that it is not allowed. However we can not uninstall the bundle again, because uninstall fails with the first mixin that fails - like trying to delete a resource that did not get installed due to the first issue.

During uninstall, I might not care if each step succeeds, but rather try to uninstall all the actions that can be uninstalled - this behaviour could be triggered with an argument like doNotFailOnError or something else - first idea was to have a "--force" to force the uninstall, but that property already have a different meaning.

An alternative could be that each mixin would allow a property like failOnError: false however the decision about the behavior then has to be taken at design time instead of at deploy time.

**Comment by carolynvs** [comment] 2021-01-08 20:19
Yay! Another vote for #592. 🎉 

For the specific helm3 retry logic for an install or upgrade, looks like there is a bug in the helm3 mixin. I just opened an issue for it https://github.com/MChorfa/porter-helm3/issues/16.

Duplicate of #592

**Comment by carolynvs** [comment] 2021-01-08 20:20
Duplicate of #592

**Comment by carolynvs** [comment] 2022-03-11 22:11
This feature is now available in the v1 prerelease https://porter.sh/blog/ignoring-errors/

**Closed** 2022-03-11 22:10 UTC
Labels: suggestion
