### ISSUE TITLE
CNCF Logo in footer is the wrong color

### ISSUE THREAD

**Issue by hrittikhere** [getporter/porter#2192] opened 2022-06-24 10:35 UTC
The CNCF Logo and sandbox project description are hidden on the website. 

![image](https://user-images.githubusercontent.com/67012359/175517838-2c00626e-1c9a-4cb9-a85f-db195ad9b621.png)

**Comment by carolynvs** [comment] 2022-06-24 13:41
I think we may have a fix for this in #2161?

**Comment by carolynvs** [comment] 2022-07-05 18:58
The logo is now
<img width="376" alt="Screen Shot 2022-07-05 at 1 57 43 PM" src="https://user-images.githubusercontent.com/1368985/177396832-f170d5a9-adc0-40d9-951b-0fac1e3c4e76.png">
 visible but it's the wrong color

Here is the correct color for the CNCF logo
<img width="536" alt="Screen Shot 2022-07-05 at 1 58 23 PM" src="https://user-images.githubusercontent.com/1368985/177396904-215e3a14-2031-4eae-a401-232a6c90c55b.png">

**Comment by hrittikhere** [comment] 2022-07-05 19:11
![image](https://user-images.githubusercontent.com/67012359/177398787-6d5c008b-2b67-403b-b152-d962e76656c7.png)
Very unique bug! If you drag the image then it shows the original one

**Comment by carolynvs** [comment] 2022-07-05 19:13
I think the problem is that the image is transparent? I'm not quite sure.

**Comment by hrittikhere** [comment] 2022-07-05 19:15
![image](https://user-images.githubusercontent.com/67012359/177399175-5a6005f5-d897-43d4-b872-51af42531803.png)
The colors are exactly inverted. The reason we need to find 

Unique and funny issue

**Comment by hrittikhere** [comment] 2022-07-05 19:16
Found our criminal. Sending a PR 😎 
![image](https://user-images.githubusercontent.com/67012359/177399453-68d91f64-14c5-4f74-ae4a-897e815504ab.png)
![image](https://user-images.githubusercontent.com/67012359/177399473-a403f368-018a-450b-a310-d2bd2b3af90a.png)

**Comment by carolynvs** [comment] 2022-07-05 19:21
TIL that CSS "filter" exists 😂

**Comment by hrittikhere** [comment] 2022-07-05 19:28
Me too. Anyways was fun for the last half an hour! Looking forward to it getting merged and there's Netlify preview waiting for us to go through

**Closed** 2022-07-05 19:32 UTC
Labels: bug, website
