### ISSUE TITLE
unable to bind porter 

### ISSUE THREAD

**Issue by sreejith1985** [getporter/porter#1385] opened 2020-12-14 10:32 UTC
Whenever I exit from the terminal, untag the porter. someone, could you please help me to fix this issue?

**Comment by vdice** [comment] 2020-12-14 17:24
@sreejith1985 I'll see what I can do to help.  First, can a bit more information be provided?  

For instance,

1. Steps to reproduce the behavior

2. The Porter commands used and their output

3. The output of `porter version`

Thank you!

**Comment by carolynvs** [comment] 2021-01-08 14:52
Closing because we did not hear back and there's not enough information to troubleshoot. If later on you are able to provide the information Vaughn requested, we'd be happy to reopen.

**Closed by carolynvs** 2021-01-08 14:52 UTC
