### ISSUE TITLE
Be able to always install the latest v1 release

### ISSUE THREAD

**Issue by LvffY** [getporter/porter#2174] opened 2022-06-19 08:12 UTC
From my point of view, it could be a good idea to have two installations links to point on each releases i.e have something like 

- Install **v0** release with  `curl -L https://cdn.porter.sh/latest/install-linux.sh | bash` (don't change this link because this is the only *stable* release but we could imagine have `curl -L https://cdn.porter.sh/latest-v0/install-linux.sh | bash` to already differentiate **v0** and **v1** releases and do ont have to think about it later)
- Install **v1** release with  `curl -L https://cdn.porter.sh/latest-v1/install-linux.sh | bash`

Of course, many options are possible here, this was just an opinion :)

**Comment by carolynvs** [comment] 2022-06-19 19:37
latest should always provide the latest stable release, which is v0.38.* Thanks for reporting that you are seeing it install v1 sometimes as that isn't what we intended!

If you have steps to reproduce that would be very helpful as I have never seen this behavior.

* Are setting the PORTER_PERMALINK environment variable?
* Which version of v1 did you see it install and which version of v0.38 were you expecting? (That would help me track down when the latest tag was incorrectly set on the v1 branch)

**Comment by LvffY** [comment] 2022-06-20 06:20
Hello @carolynvs 

I looked at my code again, and it seems I was wrong about your latest link, sorry. 

My issue is then more "Can we have a link to the latest v1 ?" than "inconsistent behavior, i'll rephrase the title and the issue.

**Comment by carolynvs** [comment] 2022-06-20 16:46
Yeah I'm with you on that. There isn't a way to do that now. Once v1 is released, "latest" will track the v1 release going forward.

Our release process is a bit complicated and I'd love to see us simplify it, by moving to goreleaser and then providing permalinks to install the latest version of each supported major version, e.g. https://cdn.porter.sh/v0/install-mac.sh and https://cdn.porter.sh/v1/install-linux.sh...

I don't have time to tackle that right now, though if anyone is interested in working on it, let's chat about what our release process needs!

**Comment by LvffY** [comment] 2022-09-24 16:48
@carolynvs i just thought about it : what about creating an [asdf plugin](todo) ?

This would do the trick about my feature request without force you to rework the release method of this project. *Actually, this could be 2 independant subjects : you of course can rework your release process, while anyone can easily download each version of porter*

**Comment by kichristensen** [comment] 2024-08-05 21:06
As the v1 version is released a long time ago, this issue will be close. Please open a new issue, if still needed

**Closed by kichristensen** 2024-08-05 21:06 UTC
Labels: meta
