### ISSUE TITLE
Update references to Debian 9 "Stretch" with Debian 11 "Bullseye"

### ISSUE THREAD

**Issue by andresbono** [getporter/porter#2746] opened 2023-04-24 14:42 UTC
## Describe the bug

Debian LTS support for Debian 9 "Stretch" ended on June 30, 2022 ([link](https://wiki.debian.org/LTS)). The package repositories for stretch are no longer available: http://deb.debian.org/debian

```
$ docker run --rm -it docker.io/debian:stretch-slim
root@5d71652fbd9f:/# apt update
Err:2 http://security.debian.org/debian-security stretch/updates Release
  404  Not Found
Err:5 http://deb.debian.org/debian stretch Release
  404  Not Found
Err:6 http://deb.debian.org/debian stretch-updates Release
  404  Not Found
```

References to Debian 9 "stretch" should be updated, for example in the Dockerfile templates for the invocation images https://github.com/getporter/porter/tree/8647f3d22253bb1fa9816144116198e0a7c9d5bf/pkg/templates/templates.

## To Reproduce

1. `porter create`
2. `porter build`

```
error building docker image: failed to solve: executor failed running [/bin/sh -c apt-get update && apt-get install -y ca-certificates]: exit code: 100
```

## Version

`porter v1.0.13 (cdaf491c)`

**Comment by carolynvs** [comment] 2023-04-24 15:25
@andresbono Thanks for the bug report!

I have a PR open to address this under #2744. I am closing your issue and will be tracking the fix under the other issue. Rest assured a new release will be cut ASAP to get the fix out.

Duplicate of #2744

**Closed by carolynvs** 2023-04-24 15:25 UTC
Labels: bug

**Comment by andresbono** [comment] 2023-04-25 09:20
Thank you for your quick reply! I saw the new release is already available. Thanks again.
