### ISSUE TITLE
Porter's autobuild check should verify the invocation image is present

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1756] opened 2021-09-14 17:14 UTC
## Describe the bug
It's possible to get into a situation where porter's check for if the bundle should be rebuilt before publishing passes but the publish fails because the invocation image isn't in the docker cache.

## To Reproduce
1. Build a bundle.
2. Remove the invocation image from your docker cache. People will do this when they run out of disk space with commands like `docker system prune`.
3. Run publish

## Expected behavior
Porter detects that the invocation image isn't available, (even though the hash of the bundle has not changed) and rebuilds the bundle before publishing.

## Porter Command and Output
I don't have the exact error message when you publish but it's basically a message from docker when we do the push of the invocation image to the registry "blah blah invocation image name: no such image found"

## Version
All versions (v0.38.4 and v1 branch)

[e.g. porter v0.14.1-beta.2 (72dd5df)]

**Comment by carolynvs** [comment] 2021-11-03 19:38
There is an existing check in porter to detect if the bundle is out of date and therefore build should be called automatically by porter before continuing to do the publish. That check should be updated to also validate that the invocation image exists. Publish shouldn't return an error, and should automatically call build for you (which is already existing logic in place, we are just updating the if statement for when to build).

**Comment by joshuabezaleel** [comment] 2021-11-16 09:59
Permission to document things while I go over trying stuffs since I might take a try on this issue 😀 
This is the error message that it outputs while I tried to reproduce the issue using the bundle `whalesay installer`.

```
Pushing CNAB invocation image...
The push refers to repository [docker.io/joshuabezaleel/whalesay-installer]
Error: unable to push CNAB invocation image "joshuabezaleel/whalesay-installer:v0.1.2": failed to stream docker push stdout: An image does not exist locally with the tag: joshuabezaleel/whalesay-installer
```

![image](https://user-images.githubusercontent.com/7043511/141963842-f7f877a7-2a34-4bff-84a2-657e3e936605.png)

**Comment by joshuabezaleel** [comment] 2022-04-27 11:50
I guess the issue can be closed since the corresponding PR has already been merged.

**Closed** 2022-04-28 21:31 UTC
Labels: bug, user experience 🌈💖
