### ISSUE TITLE
`porter install` crashing on Windows

### ISSUE THREAD

**Issue by artursouza** [getporter/porter#1209] opened 2020-08-13 23:26 UTC
## To Reproduce
1. Run `porter install` as part of the instructions on https://porter.sh/quickstart/
2. See error.

## Expected behavior
Not crash.

## Porter Command and Output
```
$ porter install
PS C:\Users\artur\porter\my-bundle> porter install
installing HELLO...
executing install action from HELLO (bundle instance: HELLO)
Install Hello World
Hello World
execution completed successfully!
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x1 pc=0x9ab11d]

goroutine 1 [running]:
github.com/cnabio/cnab-go/utils/crud.(*BackingStore).Connect(0x0, 0xc00006e700, 0x1c1400)
        /home/vsts/go/pkg/mod/github.com/vdice/cnab-go@v0.0.0-20200604175151-7484e185ff27/utils/crud/backingstore.go:23 +0x2d
github.com/cnabio/cnab-go/utils/crud.(*BackingStore).Save(0x0, 0x1bf6066, 0x6, 0xc00003a8a8, 0x5, 0xc000379300, 0xb2c, 0x103f, 0x0, 0x0)
        /home/vsts/go/pkg/mod/github.com/vdice/cnab-go@v0.0.0-20200604175151-7484e185ff27/utils/crud/backingstore.go:60 +0x52
github.com/cnabio/cnab-go/utils/crud.(*BackingStore).Save(0xc0002d3f40, 0x1bf6066, 0x6, 0xc00003a8a8, 0x5, 0xc000379300, 0xb2c, 0x103f, 0x0, 0x0)
        /home/vsts/go/pkg/mod/github.com/vdice/cnab-go@v0.0.0-20200604175151-7484e185ff27/utils/crud/backingstore.go:67 +0x114
github.com/cnabio/cnab-go/utils/crud.(*BackingStore).Save(0xc0002d3f80, 0x1bf6066, 0x6, 0xc00003a8a8, 0x5, 0xc000379300, 0xb2c, 0x103f, 0x0, 0x0)
        /home/vsts/go/pkg/mod/github.com/vdice/cnab-go@v0.0.0-20200604175151-7484e185ff27/utils/crud/backingstore.go:67 +0x114
github.com/cnabio/cnab-go/claim.Store.Save(0xc0002d3f80, 0x1c202c7, 0x13, 0xc00003a8a8, 0x5, 0xc00013eda0, 0x1a, 0xbfc590a2dda6c7d8, 0x2f255efd, 0x2d6b640, ...)
        /home/vsts/go/pkg/mod/github.com/vdice/cnab-go@v0.0.0-20200604175151-7484e185ff27/claim/claimstore.go:43 +0x142
get.porter.sh/porter/pkg/cnab/provider.(*Runtime).Install(0xc0002eadc0, 0xc00003a8a8, 0x5, 0xc0000397a0, 0x11, 0xc0001d07b0, 0xc0001d0780, 0x2d8b5e8, 0x0, 0x0, ...)
        /home/vsts/work/1/s/pkg/cnab/provider/install.go:79 +0x983
get.porter.sh/porter/pkg/porter.(*Porter).InstallBundle(0xc0002b80b0, 0x1bfe824, 0xb, 0xc0000397a0, 0x11, 0x0, 0x0, 0xc00003a8a8, 0x5, 0x0, ...)
        /home/vsts/work/1/s/pkg/porter/install.go:42 +0x39d
main.buildBundleInstallCommand.func2(0xc000340000, 0x2d8b5e8, 0x0, 0x0, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/porter/bundle.go:114 +0x85
github.com/spf13/cobra.(*Command).execute(0xc000340000, 0x2d8b5e8, 0x0, 0x0, 0xc000340000, 0x2d8b5e8)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:840 +0x467
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003d4000, 0x0, 0x18e22e0, 0xc000082058)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x31e
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
main.main()
        /home/vsts/work/1/s/cmd/porter/main.go:18 +0x2e
```

## Version
porter v0.27.2 (aee93e98)

**Comment by vdice** [comment] 2020-08-14 16:14
Hi @artursouza , thank you for the bug report.  I see in the stack trace the last calls were in a dependency library, [cnab-go](https://github.com/cnabio/cnab-go).  In v0.27.2, we pinned to a specific version.  On canary, the same dependency has most likely changed a bit.  Would it be possible to see if this same behavior is reproduced in the canary version of Porter? (https://porter.sh/install/#canary)

This will help determine if a fix is also applicable to the next Porter release.  In the meantime, I/we can look at what might be going wrong in v0.27.2 and see about the possibility of a patch release off v0.27.x...

**Comment by carolynvs** [comment] 2020-10-09 17:45
@artursouza I have confirmed that install on Windows 10 is working on `v0.29.1`. I'm working on adding a regular test to catch regressions like this in the future.

I'm going to close the issue since it's working at the moment but if you run into trouble again please let us know!

**Closed by carolynvs** 2020-10-09 17:45 UTC
Labels: bug
