### ISSUE TITLE
Parameter with space isn't treated properly

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1862] opened 2022-01-13 17:24 UTC
## Describe the bug
I have a parameter "name" and gave it a value of "demo time". When the bundle printed out the name it only printed demo. Somewhere in Porter seems like we are not quite handling parameters with spaces correctly?

## To Reproduce

1. Install the getporter/hello-llama:v0.1.1 bundle with the name parameter set to a value with a space in it, e.g. demo time

note that it only prints "Hello, demo"

## Porter Command and Output
This is output from the operator
```
$porter install -r getporter/hello-llama:v0.1.1 --param name="demo time"
executing install action from hello-llama (installation: farts)
Hello, demo
execution completed successfully!
```

## Version
v1.0.0-alpha.7

**Comment by Simpcyclassy** [comment] 2022-01-15 07:19
Hi, @carolynvs my mentor and I are looking through a couple of issues on this repo to work on during our sessions and this looks like a good start. I will like to get assigned.

cc: @sleepypioneer

**Comment by Simpcyclassy** [comment] 2022-01-16 18:07
I have been able to reproduce this bug and started to work on fixing it.

**Comment by carolynvs** [comment] 2022-01-18 19:06
Oh that's wonderful! Thanks for reproducing and looking into it. 🙇‍♀️

**Comment by Simpcyclassy** [comment] 2022-02-06 17:53
Hello, @carolynvs I am contributing to porter using a mac OS Version 11.5.2. I am unable to run `make build` without error. Below is what the error looks like

```sh
make build
```

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff2034bc9e]
```


![image](https://user-images.githubusercontent.com/34488930/152693083-714db290-c9cc-4a80-bbd4-2af7de6f15d8.png)

![image](https://user-images.githubusercontent.com/34488930/152693102-fc5dad3b-712c-4873-b250-12ecc647ea81.png)


After creating `hello-world` directory in the /tmp path and cd into it, then run `porter create` successfully. I go ahead to run the `porter build` command and here, we get the error below because of the initial `make build` not creating the mixins

```sh
porter build
```

```
Error: unable to build bundle: error while listing mixins: could not list the contents of the mixins directory "/xxx/porter/bin/mixins": open /xxx/porter/bin/mixins: no such file or directory
```

Then I have to go back and run `make build-mixins` as a hack to use the porter commands. Would this be a known issue? I took a look and did not find any. How can I get around this?

If this is not a known issue should I go ahead and file one?

**Comment by carolynvs** [comment] 2022-02-07 14:26
We want to fix this bug on the release/v1 branch, which uses a different build tool now (mage instead of make).  The problem you are seeing is because I don't believe that main is compatible with Go 1.17.

Can you check out the release/v1 branch and then try out the v1 contributor tutorial? That will help get your environment set up properly.

https://release-v1.porter.sh/contribute/tutorial/

**Comment by Simpcyclassy** [comment] 2022-02-13 17:13
We tested this and it works perfectly. When we have a fix for this issue can we branch off here as well or does it have to be from main?

**Comment by carolynvs** [comment] 2022-02-14 14:35
If you can submit a pull request against the **release/v1** branch that would be best, but if you only have it working against main, that is okay too!

**Closed** 2022-06-21 15:07 UTC
Labels: bug
